services:
  dewserver:
    build: .
    restart: always
    ports:
      - "7890:7890"
    secrets:
      - "cert.pem"
      - "key.pem"
    environment:
      SSL_CERT: "/run/secrets/cert.pem"
      SSL_KEY: "/run/secrets/key.pem" 
    volumes:
      - dew-db-data:/db-data/data.ron

secrets:
  cert.pem:
    file: ./cert.pem
  key.pem:
    file: ./key.pem

volumes:
  dew-db-data:
