services:
  dewserver:
    build: .
    restart: always
    ports:
      - "7890:7890"
    secrets:
      - "cert.pem"
      - "key.pem"
    environment:
      SSL_CERT: "/run/secrets/cert.pem"
      SSL_KEY: "/run/secrets/key.pem" 
    volumes:
      - type: bind
        source: ./db-data
        target: /db-data

secrets:
  cert.pem:
    file: ./cert.pem
  key.pem:
    file: ./key.pem

volumes:
  db-data:
